# 23-02-2026

In [1]:
import pandas as pd
import numpy as np

In [2]:
myList = [1,2,3,4]

array = np.random.randint(10,20,4)

In [3]:
print(array)
myList

[17 13 11 10]

[1, 2, 3, 4]

In [4]:
s1 = pd.Series(myList)
s1
# Series - 1D collection of data with index
# Non homogeneous data - can contain different types of data
# Indexes can be custom defined

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
s2 = pd.Series(array)
s2

0    17
1    13
2    11
3    10
dtype: int32

In [6]:
mylist = [5,4,6,1,1.7,99.8]
myarray = np.array(mylist)

In [7]:
myseries1 = pd.Series(data=mylist)
print(myseries1)
myseries2 = pd.Series(data=myarray)
print(myseries2)

df = pd.concat([myseries1,myseries2],axis=1)
print(df)
df = pd.concat([myseries1,myseries2],axis=0) # DataFrame - 2D collection of data with index and columns
print(df)

0     5.0
1     4.0
2     6.0
3     1.0
4     1.7
5    99.8
dtype: float64
0     5.0
1     4.0
2     6.0
3     1.0
4     1.7
5    99.8
dtype: float64
      0     1
0   5.0   5.0
1   4.0   4.0
2   6.0   6.0
3   1.0   1.0
4   1.7   1.7
5  99.8  99.8
0     5.0
1     4.0
2     6.0
3     1.0
4     1.7
5    99.8
0     5.0
1     4.0
2     6.0
3     1.0
4     1.7
5    99.8
dtype: float64

In [8]:
mylables = ['first', 'second', 'third', 'fourth']
# myseries3 = pd.Series(data=mylist, index=mylables)
# print(myseries3)
myseries4 = pd.Series(data=myarray, index=mylist)
print(myseries4)

5.0      5.0
4.0      4.0
6.0      6.0
1.0      1.0
1.7      1.7
99.8    99.8
dtype: float64

# 25-02-2026

In [9]:
# Series from Dictonary
s3 = pd.Series({'apple':7, 'mango':18, 'banana':45})
s3

apple      7
mango     18
banana    45
dtype: int64

In [10]:
print("Values: ", s3.values)
print("Indexes: ", s3.index)

Values:  [ 7 18 45]
Indexes:  Index(['apple', 'mango', 'banana'], dtype='str')

In [11]:
df1 = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [10, 20, 30]
})
print(df1)

   A   B
0  1  10
1  2  20
2  3  30

In [12]:
# Basic Attributes of DataFrame
print("Shape: ", df1.shape)
print("Coloumns: ", df1.columns)
print("Index: ", df1.index)
print("Data Types: ", df1.dtypes)

Shape:  (3, 2)
Coloumns:  Index(['A', 'B'], dtype='str')
Index:  RangeIndex(start=0, stop=3, step=1)
Data Types:  A    int64
B    int64
dtype: object

In [13]:
df1.head() # Default 5 rows

   A   B
0  1  10
1  2  20
2  3  30

In [14]:
df1.tail() # Default last 5 rows

   A   B
0  1  10
1  2  20
2  3  30

In [15]:
df1.head(1)

   A   B
0  1  10

In [16]:
df1.tail(1)

   A   B
2  3  30

In [17]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
dtypes: int64(2)
memory usage: 180.0 bytes

In [18]:
# Statistical Summary
df1.describe()

         A     B
count  3.0   3.0
mean   2.0  20.0
std    1.0  10.0
min    1.0  10.0
25%    1.5  15.0
50%    2.0  20.0
75%    2.5  25.0
max    3.0  30.0

In [19]:
df1.describe().T

   count  mean   std   min   25%   50%   75%   max
A    3.0   2.0   1.0   1.0   1.5   2.0   2.5   3.0
B    3.0  20.0  10.0  10.0  15.0  20.0  25.0  30.0

In [20]:
df2 = pd.DataFrame({"Name": ["John", "Jane", "Doe"], "Age": [25, 30, 35], 'Salary': [50000, 60000, 70000]})
print(df2)

   Name  Age  Salary
0  John   25   50000
1  Jane   30   60000
2   Doe   35   70000

In [21]:
print("Summary: ", df2.info())
print("\nStatistical Summary:\n", df2.describe().T)

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   Salary  3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes
Summary:  None

Statistical Summary:
         count     mean      std      min      25%      50%      75%      max
Age       3.0     30.0      5.0     25.0     27.5     30.0     32.5     35.0
Salary    3.0  60000.0  10000.0  50000.0  55000.0  60000.0  65000.0  70000.0

In [22]:
# Full satistics summary of the data
df2.describe(include='all')

        Name   Age   Salary
count      3   3.0      3.0
unique     3   NaN      NaN
top     John   NaN      NaN
freq       1   NaN      NaN
mean     NaN  30.0  60000.0
std      NaN   5.0  10000.0
min      NaN  25.0  50000.0
25%      NaN  27.5  55000.0
50%      NaN  30.0  60000.0
75%      NaN  32.5  65000.0
max      NaN  35.0  70000.0

In [23]:
# Alphanumeric dataframe example
df3 = pd.DataFrame({
    "Name": ["John", "Jane", "Doe", "Smith", "Emily", "Roman"],
    "Age": [25, 30, 35, 40, 45, 50],
    "City": ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'New York'],
    'Salary': [50000, 60000, 70000, 80000, 90000, 100000],
    'Department': ['HR', 'Finance', 'IT', 'Marketing', 'HR', 'IT']
})

In [24]:
# Statistical Summary
df3.describe(include='all') # Include all data types in the summary

        Name        Age      City         Salary Department
count      6   6.000000         6       6.000000          6
unique     6        NaN         5            NaN          4
top     John        NaN  New York            NaN         HR
freq       1        NaN         2            NaN          2
mean     NaN  37.500000       NaN   75000.000000        NaN
std      NaN   9.354143       NaN   18708.286934        NaN
min      NaN  25.000000       NaN   50000.000000        NaN
25%      NaN  31.250000       NaN   62500.000000        NaN
50%      NaN  37.500000       NaN   75000.000000        NaN
75%      NaN  43.750000       NaN   87500.000000        NaN
max      NaN  50.000000       NaN  100000.000000        NaN

In [25]:
df3

    Name  Age         City  Salary Department
0   John   25     New York   50000         HR
1   Jane   30  Los Angeles   60000    Finance
2    Doe   35      Chicago   70000         IT
3  Smith   40      Houston   80000  Marketing
4  Emily   45      Phoenix   90000         HR
5  Roman   50     New York  100000         IT

In [26]:
df3["Salary"].unique()

array([ 50000,  60000,  70000,  80000,  90000, 100000])

In [27]:
df3.Department.value_counts()

Department
HR           2
IT           2
Finance      1
Marketing    1
Name: count, dtype: int64

# 27-02-2026

In [28]:
print("Single Coloumn (Series):\n", df3["Name"])
print("\nMultiple Coloumns (DataFrame):\n", df3[["Name", "Salary"]])

Single Coloumn (Series):
 0     John
1     Jane
2      Doe
3    Smith
4    Emily
5    Roman
Name: Name, dtype: str

Multiple Coloumns (DataFrame):
     Name  Salary
0   John   50000
1   Jane   60000
2    Doe   70000
3  Smith   80000
4  Emily   90000
5  Roman  100000

In [29]:
df3.loc[0] # Accessing first row using loc

Name              John
Age                 25
City          New York
Salary           50000
Department          HR
Name: 0, dtype: object

In [30]:
df3.iloc[0] # Accessing first row using iloc

Name              John
Age                 25
City          New York
Salary           50000
Department          HR
Name: 0, dtype: object

In [31]:
import pandas as pd
import numpy as np

In [32]:
df4 = pd.DataFrame(np.arange(1,26).reshape(5, 5), index=['first row', 'second row', 'third row', 'fourth row', 'fifth row'],
                   columns=['first coloumn', 'second coloumn', 'third coloumn', 'fourth coloumn', 'fifth coloumn'])
df4

,first coloumn,second coloumn,third coloumn,fourth coloumn,fifth coloumn
first row,1,2,3,4,5
second row,6,7,8,9,10
third row,11,12,13,14,15
fourth row,16,17,18,19,20
fifth row,21,22,23,24,25

In [33]:
df4.loc["first row", "first coloumn"] # Accessing specific cell using loc

np.int64(1)

In [34]:
# df4.loc(1, 2)

In [35]:
df4.iloc[1, 2]

np.int64(8)

In [36]:
df4.iloc[1:,:2]

            first coloumn  second coloumn
second row              6               7
third row              11              12
fourth row             16              17
fifth row              21              22

In [37]:
df4.iloc[1:2,3::-1]

            fourth coloumn  third coloumn  second coloumn  first coloumn
second row               9              8               7              6

In [38]:
df4.iloc[4::-2,2::-2]

           third coloumn  first coloumn
fifth row             23             21
third row             13             11
first row              3              1

In [39]:
df4.iloc[::-2,5::-2] # Extra range can be given, it will not throw error but will return the available data in the range.

           fifth coloumn  third coloumn  first coloumn
fifth row             25             23             21
third row             15             13             11
first row              5              3              1

## Reading Files

In [40]:
import pandas as pd
import numpy as np

In [41]:
df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

In [42]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [43]:
survived = df[(df["Survived"] == 1) & (df["Age"] < 30)]
survived.sort_values(by='Fare')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
271,272,1,3,"Tornquist, Mr. William Henry",male,25.0,0,0,LINE,0.0000,NaN,S
804,805,1,3,"Hedman, Mr. Oskar Arvid",male,27.0,0,0,347089,6.9750,NaN,S
127,128,1,3,"Madsen, Mr. Fridtjof Arne",male,24.0,0,0,C 17369,7.1417,NaN,S
553,554,1,3,"Leeni, Mr. Fahim (""Philip Zenni"")",male,22.0,0,0,2620,7.2250,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0,1,0,PC 17757,227.5250,C62 C64,C
311,312,1,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
742,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,19950,263.0000,C23 C25 C27,S

In [44]:
df.sort_values(by='Age')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

# 06-0-2026

### Boolean Indexing

In [45]:
df3

    Name  Age         City  Salary Department
0   John   25     New York   50000         HR
1   Jane   30  Los Angeles   60000    Finance
2    Doe   35      Chicago   70000         IT
3  Smith   40      Houston   80000  Marketing
4  Emily   45      Phoenix   90000         HR
5  Roman   50     New York  100000         IT

In [46]:
high_salary = df3[df3["Salary"] > 50000]
print("Employees with high salary:\n", high_salary)

Employees with high salary:
     Name  Age         City  Salary Department
1   Jane   30  Los Angeles   60000    Finance
2    Doe   35      Chicago   70000         IT
3  Smith   40      Houston   80000  Marketing
4  Emily   45      Phoenix   90000         HR
5  Roman   50     New York  100000         IT

In [47]:
salary = df3[((df3["Salary"] == 50000) | (df3["City"] == 'New York'))]
print("Employees with salary 50000 or from New York:\n", salary)

Employees with salary 50000 or from New York:
     Name  Age      City  Salary Department
0   John   25  New York   50000         HR
5  Roman   50  New York  100000         IT

In [48]:
salary = df3[((df3["Salary"] == 50000) & (df3["City"] == 'New York'))]
salary

   Name  Age      City  Salary Department
0  John   25  New York   50000         HR

In [49]:
salary1 = df3[(df3["Age"] != 25) & (df3["Salary"] != 70000)]
salary1

    Name  Age         City  Salary Department
1   Jane   30  Los Angeles   60000    Finance
3  Smith   40      Houston   80000  Marketing
4  Emily   45      Phoenix   90000         HR
5  Roman   50     New York  100000         IT

In [50]:
df3_renamed = df3.rename(columns={"Name": "Employee", "Salary": "Income"})
df3_renamed

  Employee  Age         City  Income Department
0     John   25     New York   50000         HR
1     Jane   30  Los Angeles   60000    Finance
2      Doe   35      Chicago   70000         IT
3    Smith   40      Houston   80000  Marketing
4    Emily   45      Phoenix   90000         HR
5    Roman   50     New York  100000         IT

# 09-03-2025

In [51]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [52]:

df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [53]:
df.value_counts()

PassengerId  Survived  Pclass  Name                                                 Sex     Age   SibSp  Parch  Ticket    Fare     Cabin        Embarked
2            1         1       Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0  1      0      PC 17599  71.2833  C85          C           1
4            1         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)         female  35.0  1      0      113803    53.1000  C123         S           1
7            0         1       McCarthy, Mr. Timothy J                              male    54.0  0      0      17463     51.8625  E46          S           1
11           1         3       Sandstrom, Miss. Marguerite Rut                      female  4.0   1      1      PP 9549   16.7000  G6           S           1
12           1         1       Bonnell, Miss. Elizabeth                             female  58.0  0      0      113783    26.5500  C103         S           1
                                                                                                                                                           ..
872          1         1       Beckwith, Mrs. Richard Leonard (Sallie Monypeny)     female  47.0  1      1      11751     52.5542  D35          S           1
873          0         1       Carlsson, Mr. Frans Olof                             male    33.0  0      0      695       5.0000   B51 B53 B55  S           1
880          1         1       Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)        female  56.0  0      1      11767     83.1583  C50          C           1
888          1         1       Graham, Miss. Margaret Edith                         female  19.0  0      0      112053    30.0000  B42          S           1
890          1         1       Behr, Mr. Karl Howell                                male    26.0  0      0      111369    30.0000  C148         C           1
Name: count, Length: 183, dtype: int64

In [54]:
df.value_counts('Survived')

Survived
0    549
1    342
Name: count, dtype: int64

In [55]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q