In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/Users/samarth/Downloads/car_sales_data.csv")

In [3]:
df

,Manufacturer,Model,Engine size,Fuel type,Year of manufacture,Mileage,Price
0,Ford,Fiesta,1.0,Petrol,2002,127300,3074
1,Porsche,718 Cayman,4.0,Petrol,2016,57850,49704
2,Ford,Mondeo,1.6,Diesel,2014,39190,24072
3,Toyota,RAV4,1.8,Hybrid,1988,210814,1705
4,VW,Polo,1.0,Petrol,2006,127869,4101
...,...,...,...,...,...,...,...
49995,BMW,M5,5.0,Petrol,2018,28664,113006
49996,Toyota,Prius,1.8,Hybrid,2003,105120,9430
49997,Ford,Mondeo,1.6,Diesel,2022,4030,49852
49998,Ford,Focus,1.0,Diesel,2016,26468,23630
49999,VW,Golf,1.4,Diesel,2012,109300,10400

In [4]:
df.head(15)

,Manufacturer,Model,Engine size,Fuel type,Year of manufacture,Mileage,Price
0,Ford,Fiesta,1.0,Petrol,2002,127300,3074
1,Porsche,718 Cayman,4.0,Petrol,2016,57850,49704
2,Ford,Mondeo,1.6,Diesel,2014,39190,24072
3,Toyota,RAV4,1.8,Hybrid,1988,210814,1705
4,VW,Polo,1.0,Petrol,2006,127869,4101
5,Ford,Focus,1.4,Petrol,2018,33603,29204
6,Ford,Mondeo,1.8,Diesel,2010,86686,14350
7,Toyota,Prius,1.4,Hybrid,2015,30663,30297
8,VW,Polo,1.2,Petrol,2012,73470,9977
9,Ford,Focus,2.0,Diesel,1992,262514,1049
10,VW,Golf,2.0,Diesel,2014,83047,17173
11,BMW,Z4,2.0,Petrol,1990,293666,719
12,VW,Golf,1.2,Diesel,2007,92697,7792
13,Toyota,RAV4,2.2,Petrol,2007,79393,16026
14,Toyota,Yaris,1.4,Petrol,1998,97286,4046

In [5]:
df.isnull().sum()

Manufacturer           0
Model                  0
Engine size            0
Fuel type              0
Year of manufacture    0
Mileage                0
Price                  0
dtype: int64

In [6]:
df.tail(15)

,Manufacturer,Model,Engine size,Fuel type,Year of manufacture,Mileage,Price
49985,VW,Passat,1.8,Diesel,2004,145451,6501
49986,Ford,Focus,1.6,Petrol,2013,20916,24041
49987,Toyota,Prius,1.4,Hybrid,2011,70499,18102
49988,Ford,Mondeo,1.6,Diesel,1990,142328,2339
49989,Ford,Fiesta,1.2,Diesel,2000,79154,4412
49990,Toyota,RAV4,2.4,Hybrid,2001,39250,17434
49991,Toyota,RAV4,2.0,Hybrid,2004,105792,12427
49992,VW,Polo,1.4,Petrol,2012,48057,12703
49993,Ford,Mondeo,1.8,Petrol,2003,120969,6654
49994,Toyota,RAV4,1.8,Hybrid,2002,101634,10639
49995,BMW,M5,5.0,Petrol,2018,28664,113006
49996,Toyota,Prius,1.8,Hybrid,2003,105120,9430
49997,Ford,Mondeo,1.6,Diesel,2022,4030,49852
49998,Ford,Focus,1.0,Diesel,2016,26468,23630
49999,VW,Golf,1.4,Diesel,2012,109300,10400

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Manufacturer         50000 non-null  object
 1   Model                50000 non-null  object
 2   Engine size          50000 non-null  float64
 3   Fuel type            50000 non-null  object
 4   Year of manufacture  50000 non-null  int64
 5   Mileage              50000 non-null  int64
 6   Price                50000 non-null  int64
dtypes: float64(1), int64(3), object(3)
memory usage: 2.7+ MB

In [8]:
df.describe()

        Engine size  Year of manufacture        Mileage          Price
count  50000.000000         50000.000000   50000.000000   50000.000000
mean       1.773058          2004.209440  112497.320700   13828.903160
std        0.734108             9.645965   71632.515602   16416.681336
min        1.000000          1984.000000     630.000000      76.000000
25%        1.400000          1996.000000   54352.250000    3060.750000
50%        1.600000          2004.000000  100987.500000    7971.500000
75%        2.000000          2012.000000  158601.000000   19026.500000
max        5.000000          2022.000000  453537.000000  168081.000000

In [9]:
df.Manufacturer.value_counts()

Manufacturer
Ford       14959
VW         14913
Toyota     12554
BMW         4965
Porsche     2609
Name: count, dtype: int64

In [10]:
df["Model"].unique()

array(['Fiesta', '718 Cayman', 'Mondeo', 'RAV4', 'Polo', 'Focus', 'Prius',
       'Golf', 'Z4', 'Yaris', '911', 'Passat', 'M5', 'Cayenne', 'X3'],
      dtype=object)

In [16]:
df[(df["Manufacturer"] == "BMW")]

,Manufacturer,Model,Engine size,Fuel type,Year of manufacture,Mileage,Price
11,BMW,Z4,2.0,Petrol,1990,293666,719
37,BMW,Z4,2.2,Petrol,2005,133174,8511
39,BMW,Z4,2.0,Petrol,1990,148586,2637
41,BMW,M5,4.0,Petrol,2017,22759,97758
44,BMW,Z4,2.0,Petrol,1995,42759,7873
...,...,...,...,...,...,...,...
49956,BMW,Z4,2.4,Petrol,2015,59520,29466
49966,BMW,X3,3.0,Diesel,2006,106873,14336
49969,BMW,Z4,2.2,Petrol,2013,33773,28921
49976,BMW,M5,4.0,Petrol,1994,211856,5106
49995,BMW,M5,5.0,Petrol,2018,28664,113006

In [12]:
df[(df["Manufacturer"] == "BMW") & (df["Year of manufacture"]>2000)]

,Manufacturer,Model,Engine size,Fuel type,Year of manufacture,Mileage,Price
37,BMW,Z4,2.2,Petrol,2005,133174,8511
41,BMW,M5,4.0,Petrol,2017,22759,97758
58,BMW,Z4,2.2,Petrol,2004,126777,8373
101,BMW,M5,4.4,Petrol,2008,109941,31711
108,BMW,Z4,2.2,Petrol,2018,32319,40706
...,...,...,...,...,...,...,...
49948,BMW,X3,2.4,Diesel,2012,71834,24526
49956,BMW,Z4,2.4,Petrol,2015,59520,29466
49966,BMW,X3,3.0,Diesel,2006,106873,14336
49969,BMW,Z4,2.2,Petrol,2013,33773,28921
49995,BMW,M5,5.0,Petrol,2018,28664,113006

In [13]:
#groupby concept
#1. Average Price by Manufacturer
avg_price = df.groupby('Manufacturer')['Price'].sum()
print(avg_price)

Manufacturer
BMW        121292265
Ford       159646767
Porsche     75931722
Toyota     180028908
VW         154545496
Name: Price, dtype: int64

In [14]:
#2. Total Cars Sold (Count) by Manufacturer
car_count = df.groupby('Manufacturer')['Model'].count()
print(car_count)

Manufacturer
BMW         4965
Ford       14959
Porsche     2609
Toyota     12554
VW         14913
Name: Model, dtype: int64

In [15]:
#3. Average Mileage by Fuel Type
avg_mileage = df.groupby('Fuel type')['Mileage'].mean().reset_index()
print(avg_mileage)

  Fuel type        Mileage
0    Diesel  112667.486584
1    Hybrid  111622.108502
2    Petrol  112794.838159

In [16]:
#4.Multiple Aggregations (Mean and Max Price)
price_stats = df.groupby('Manufacturer')['Price'].agg(['mean', 'max','min'])
print(price_stats)

                      mean     max  min
Manufacturer
BMW           24429.459215  168081  167
Ford          10672.288723   62748   85
Porsche       29103.764661  167774  266
Toyota        14340.362275   86353  176
VW            10363.139274   58588   76

In [17]:
#5. Group by Two Columns (Manufacturer & Fuel Type)
group_two = df.groupby(['Manufacturer', 'Fuel type'])['Price'].mean()
print(group_two)

Manufacturer  Fuel type
BMW           Diesel       18148.220392
              Petrol       26599.805962
Ford          Diesel       12568.304034
              Hybrid       12599.549852
              Petrol        9071.918729
Porsche       Diesel       28247.090580
              Petrol       29205.111444
Toyota        Hybrid       15329.371990
              Petrol       10951.364951
VW            Diesel       11925.211813
              Hybrid       12389.113060
              Petrol        9159.206982
Name: Price, dtype: float64

In [18]:
#6. Sorting the Grouped Results
avg_price_sorted = df.groupby('Manufacturer')['Price'].mean().sort_values(ascending=False)
print(avg_price_sorted.head(10))

Manufacturer
Porsche    29103.764661
BMW        24429.459215
Toyota     14340.362275
Ford       10672.288723
VW         10363.139274
Name: Price, dtype: float64

In [19]:
#7. Count and Average Together
summary = df.groupby('Manufacturer').agg(
    total_cars=('Model', 'count'),
    avg_price=('Price', 'mean')
)
print(summary)

              total_cars     avg_price
Manufacturer
BMW                 4965  24429.459215
Ford               14959  10672.288723
Porsche             2609  29103.764661
Toyota             12554  14340.362275
VW                 14913  10363.139274

In [20]:
#8. Displaying Results as a DataFrame
summary_df = df.groupby('Fuel type')[['Mileage', 'Price']].mean().reset_index()
print(summary_df)

  Fuel type        Mileage         Price
0    Diesel  112667.486584  13145.078158
1    Hybrid  111622.108502  14949.288154
2    Petrol  112794.838159  13690.617742

In [21]:
top_index = df.groupby('Manufacturer')['Price'].idxmin()
top_cars = df.loc[top_index][['Manufacturer', 'Model', 'Price','Fuel type']]
print(top_cars)
print("====")
# print(top_index)

      Manufacturer       Model  Price Fuel type
41039          BMW          X3    167    Diesel
44452         Ford      Fiesta     85    Petrol
10480      Porsche  718 Cayman    266    Petrol
1047        Toyota       Prius    176    Hybrid
18063           VW        Polo     76    Petrol
====

In [22]:
df.nlargest(5, 'Price')    # top 5 most expensive cars

,Manufacturer,Model,Engine size,Fuel type,Year of manufacture,Mileage,Price
22786,BMW,M5,5.0,Petrol,2022,4590,168081
14860,BMW,M5,5.0,Petrol,2022,4683,168001
38438,Porsche,911,3.5,Petrol,2022,2931,167774
49362,Porsche,911,3.5,Petrol,2022,6963,164343
38166,BMW,M5,5.0,Petrol,2022,9797,163608

In [23]:
df.nsmallest(10, 'Mileage') # 5 cars with least mileage

,Manufacturer,Model,Engine size,Fuel type,Year of manufacture,Mileage,Price
30697,VW,Golf,1.8,Diesel,2022,630,45601
20045,Toyota,RAV4,1.8,Hybrid,2022,664,75692
36576,VW,Golf,1.4,Petrol,2022,770,38274
18313,VW,Polo,1.2,Petrol,2021,1000,27901
23927,VW,Polo,1.2,Petrol,2021,1000,27901
26413,BMW,Z4,2.2,Petrol,2022,1027,62960
39943,BMW,X3,2.0,Diesel,2022,1028,66183
25349,VW,Polo,2.0,Petrol,2022,1197,38466
38725,VW,Polo,1.6,Petrol,2022,1340,34380
24675,BMW,M5,5.0,Petrol,2021,1437,159778

In [24]:
df2 = pd.read_csv("/Users/samarth/Downloads/car_sales_teaching_raw.csv")

In [25]:
print(df2.head())

      Brand      Model  Year  Units_Sold  Price_USD      Dealer
0      Tata  Hatchback  2016      4500.0    30000.0  MegaMotors
1       BMW        SUV  2024      2000.0        NaN   SpeedCars
2  Mercedes      Truck  2018      3000.0        NaN   AutoWorld
3      Tata      Truck  2030       500.0    30000.0    ZoomCars
4      Ford  Hatchback  2021      1500.0        NaN    DriveNow

In [26]:
df2.shape

(45, 6)

In [27]:
df2.isna().sum()

Brand          0
Model          0
Year           0
Units_Sold    14
Price_USD     12
Dealer         3
dtype: int64

In [28]:
df.duplicated().sum()

np.int64(12)

In [29]:
df2["Brand"].fillna("Unknown")
df2["Dealer"].fillna("Not Assigned")

0       MegaMotors
1        SpeedCars
2        AutoWorld
3         ZoomCars
4         DriveNow
5        AutoWorld
6       MegaMotors
7     Not Assigned
8        SpeedCars
9       MegaMotors
10       AutoWorld
11       SpeedCars
12        DriveNow
13       AutoWorld
14      MegaMotors
15          CarMax
16        ZoomCars
17    Not Assigned
18      MegaMotors
19       SpeedCars
20       AutoWorld
21        ZoomCars
22       AutoWorld
23       SpeedCars
24       AutoWorld
25          CarMax
26        ZoomCars
27        ZoomCars
28       SpeedCars
29    Not Assigned
30          CarMax
31      MegaMotors
32       AutoWorld
33        DriveNow
34       AutoWorld
35       AutoWorld
36      MegaMotors
37       AutoWorld
38          CarMax
39          CarMax
40       AutoWorld
41      MegaMotors
42        ZoomCars
43        ZoomCars
44        ZoomCars
Name: Dealer, dtype: object

In [30]:
df2["Units_Sold"].fillna(df2["Units_Sold"].mean())
df2["Price_USD"].fillna(df2["Price_USD"].mean())

0     30000.000000
1     13121.212121
2     13121.212121
3     30000.000000
4     13121.212121
5     15000.000000
6     -5000.000000
7     22000.000000
8     30000.000000
9     35000.000000
10    13121.212121
11    15000.000000
12    15000.000000
13   -10000.000000
14    22000.000000
15     8000.000000
16     8000.000000
17    30000.000000
18   -10000.000000
19    13121.212121
20    30000.000000
21   -10000.000000
22    22000.000000
23    22000.000000
24    22000.000000
25    22000.000000
26    22000.000000
27   -10000.000000
28   -10000.000000
29    15000.000000
30    35000.000000
31     8000.000000
32    13121.212121
33    22000.000000
34    13121.212121
35    13121.212121
36   -10000.000000
37    13121.212121
38    13121.212121
39    13121.212121
40    13121.212121
41     8000.000000
42    30000.000000
43   -10000.000000
44   -10000.000000
Name: Price_USD, dtype: float64

In [31]:
print(df2.isna().sum())

Brand          0
Model          0
Year           0
Units_Sold    14
Price_USD     12
Dealer         3
dtype: int64

In [32]:
df.drop_duplicates(inplace=True)

In [33]:
import pandas as pd

data = {
    'Region': ['East', 'West', 'East', 'West', 'East'],
    'Product': ['Pen', 'Pen', 'Pencil', 'Pencil', 'Pen'],
    'Sales': [120, 80, 50, 90, 100]
}

df = pd.DataFrame(data)
print(df)

  Region Product  Sales
0   East     Pen    120
1   West     Pen     80
2   East  Pencil     50
3   West  Pencil     90
4   East     Pen    100

In [34]:
pivot = pd.pivot_table(df, values='Sales', index='Region', columns='Product', aggfunc='sum')
print(pivot)

Product  Pen  Pencil
Region
East     220      50
West      80      90

In [35]:
pd.pivot_table(df, values='Sales', index='Region', columns='Product', aggfunc='mean')

Product    Pen  Pencil
Region
East     110.0    50.0
West      80.0    90.0

In [36]:
pd.pivot_table(df, values='Sales', index='Region', columns='Product', aggfunc='count')

Product  Pen  Pencil
Region
East       2       1
West       1       1

In [37]:
pd.pivot_table(df, values='Sales', index=['Region'], columns=['Product'], aggfunc=['sum', 'mean'])

         sum          mean
Product  Pen Pencil    Pen Pencil
Region
East     220     50  110.0   50.0
West      80     90   80.0   90.0

In [38]:
pivot = pd.pivot_table(df, values='Sales', index='Region', columns='Product', aggfunc='sum', fill_value=0)

In [39]:
import pandas as pd

data = {
    'Date': ['2025-01-01', '2025-01-01', '2025-01-02', '2025-01-02', '2025-01-03', '2025-01-03', '2025-01-04'],
    'Region': ['East', 'East', 'West', 'South', 'East', 'West', 'South'],
    'Product': ['Pen', 'Notebook', 'Pencil', 'Mug', 'Mug', 'Pen', 'Notebook'],
    'Category': ['Stationery', 'Stationery', 'Stationery', 'Gift', 'Gift', 'Stationery', 'Stationery'],
    'Sales': [120, 200, 100, 250, 300, 90, 180],
    'Quantity': [10, 5, 8, 4, 6, 7, 3]
}

df = pd.DataFrame(data)
print(df)

         Date Region   Product    Category  Sales  Quantity
0  2025-01-01   East       Pen  Stationery    120        10
1  2025-01-01   East  Notebook  Stationery    200         5
2  2025-01-02   West    Pencil  Stationery    100         8
3  2025-01-02  South       Mug        Gift    250         4
4  2025-01-03   East       Mug        Gift    300         6
5  2025-01-03   West       Pen  Stationery     90         7
6  2025-01-04  South  Notebook  Stationery    180         3

In [40]:
#Total Sales by Region
pivot1 = pd.pivot_table(df, values='Sales', index='Region', aggfunc='sum')
print(pivot1)

        Sales
Region
East      620
South     430
West      190

In [41]:
#Sales by Region and Category
pivot2 = pd.pivot_table(df, values='Sales', index='Region', columns='Category', aggfunc='sum', fill_value=0)
print(pivot2)

Category  Gift  Stationery
Region
East       300         320
South      250         180
West         0         190

In [42]:
#Multiple Aggregations (Sum and Mean)
pivot3 = pd.pivot_table(
    df,
    values='Sales',
    index='Region',
    columns='Category',
    aggfunc=['sum', 'mean'],
    fill_value=0
)
print(pivot3)

          sum              mean
Category Gift Stationery   Gift Stationery
Region
East      300        320  300.0      160.0
South     250        180  250.0      180.0
West        0        190    0.0       95.0

In [43]:
#Analyze Total Quantity per Product
pivot4 = pd.pivot_table(df, values='Quantity', index='Product', aggfunc='sum')
print(pivot4)

          Quantity
Product
Mug             10
Notebook         8
Pen             17
Pencil           8

In [44]:
#Combine Multiple Values
pivot5 = pd.pivot_table(
    df,
    values=['Sales', 'Quantity'],
    index='Region',
    columns='Category',
    aggfunc='sum',
    fill_value=0
)
print(pivot5)

         Quantity            Sales
Category     Gift Stationery  Gift Stationery
Region
East            6         15   300        320
South           4          3   250        180
West            0         15     0        190

In [45]:
pivot5.columns = ['_'.join(col).strip() for col in pivot5.columns.values]
print(pivot5)

        Quantity_Gift  Quantity_Stationery  Sales_Gift  Sales_Stationery
Region
East                6                   15         300               320
South               4                    3         250               180
West                0                   15           0               190